#!/bin/bash
#This script has been created for the ChIP-seq data analysis tutorial publicated in:
# Joaqun Giner-Lamia, Miguel Hernández-Prieto, M.E. Futschik. "ChIP-seq Experiment and Data Analysis in the Cyanobacterium Synechocystis sp. PCC 6803". 2018. bio-protocols
# For more information visit the wiki Github page: https://github.com/ginerorama/NtcA-bio-protocols-tutorial/wiki

# Note: This bash script contains all the command line used in the ChIP-seq tutorial. 
# By default shell script will not run. You need to set execute permission for your shell script. 
# To give permission type the following command: $ chmod +x ChIP-seq_scripts
# To execute or run the script: $ . ChIP-seq_scripts 
# execute this script after move it into the folder where you cloned all the tutorial files.
# uncompress the fastq.zip files!!!

################### Alignment of the reads using Bowtie2
echo Alignment of the reads using Bowtie2

#Genome index generation:
echo 1.Genome index generation
bowtie2-build NC_000911.1.fasta Synechocystis


#Line command to align the ChIP-samples:
echo 2.aligning ChIP-samples
Bowtie2 -x Synechocystis -U N_ChIP.fastq -S N_ChIP.sam
Bowtie2 -x Synechocystis -U N_Input.fastq -S N_Input.sam



################### SAM to BAM
echo SAM to BAM

#SAM to BAM:
echo 1.SAM to BAM
samtools view -bS N_Input.sam > N_Input.bam
samtools view -bS N_ChIP.sam > N_ChIP.bam

#Sorting BAM files:
echo 2.Sorting BAM files
samtools sort N_Input.bam > N_Input_sorted.bam
samtools sort N_ChIP.bam > N_ChIP_sorted.bam

#indexing BAM files:
echo 3.indexing BAM files
samtools index N_Input_sorted.bam
samtools index N_ChIP_sorted.bam


################### DeepTool2: Creating BigWig files 
echo DeepTool2: Creating BigWig files 


bamCoverage -b N_Input_sorted.bam -o N_Input.bw --normalizeUsingRPKM
bamCoverage -b N_ChIP_sorted.bam -o N_ChIP.bw --normalizeUsingRPKM



################### Peak Calling analysis with MACS
echo Peak Calling analysis with MACS

macs14 –t N_ChIP_sorted.bam -c N_Input_sorted.bam -g 3.5e6 -n NtcA_N --bw 200 --nomodel --shiftsize 50


echo Finished!!
###################################################################################################
#
